version: '2' # version docker compose
services:

  # Php container
  php:
    container_name: laravel_php
    build: ./docker-php # Point to path Dockerfile for create container
    working_dir: /var/www/laravel
    volumes:
      # local : Container
      - ./:/var/www/laravel 

  # Web Server (nginx container)
  nginx:
    build: ./docker-nginx
    working_dir: /var/www/laravel
    volumes_from:
      - php # from php container
    ports:
      - 8000:80 # port {host}:{container}

  # Database (mysql container)
  database:
    # pull image (No Dockerfile) 
    image: mysql:5.7 
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      # config https://hub.docker.com/_/mysql/
      - MYSQL_DATABASE=laravel # database name
      - MYSQL_USER=user # username
      - MYSQL_PASSWORD=password # password
      - MYSQL_ROOT_PASSWORD=root # password for root
    ports:
        - "3306:3306" # port {host}:{container}

  composer: # container for install package laravel
    build: ./docker-php # use same as container php
    working_dir: /var/www/laravel
    volumes_from:
      - php
    command: "composer install" # install package

  # Phpmyadmin (optional)
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - 8890:80
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=database
    restart: always
    depends_on:
        - database